#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  4 14:14:02 2017

@author: JingGuo

This script preprocess the annotated labels. 
The output is [file_id, mean_score], where mean_score is from {0,1,2,3,4,5,6}

TODO: 
    Add strict criteria to generate different dataset to remove bias. 
    For example: remove the current data point if there is a large disagreement
    between annotations.

"""

import csv

# use use_sample for debugging
use_sample = False
sample_file = "./raw_data/sample.csv"
raw_annotations = "./raw_data/MTurkAnnotations.csv"

file = open(sample_file) if use_sample else open(raw_annotations)

# name of the output file
output_file_name = "processed_labels_no_criteria.csv"

ids = []
scores = []

for line in file:
    information = line.rstrip().split(',')
    
    file_id = information[0]
    number_of_score = 0
    sum_of_score = 0.0
    
    for idx, score in enumerate(information):
        if idx == 0:
            continue
        if score == 'ambiguous':
            continue
        number_of_score = number_of_score + 1
        sum_of_score = sum_of_score + float(score)
    
    # criteria for removing bias
    if True:
        ids.append(file_id)
        scores.append(int(round(sum_of_score/number_of_score)))

# write the result into a csv file.
with open(output_file_name, 'w') as output_file:
    writer = csv.writer(output_file, delimiter=',')
    for idx, file_id in enumerate(ids):
        writer.writerow([file_id, scores[idx] + 3])
        
    

    